### ISSUE TITLE
Error when running yarn build after forking repo to add new SVG logo

### ISSUE THREAD

**Issue by AMIRKHANEF** [opensquare-network/icons#6]
Hi,

I would like to add a new SVG logo to this repository. I have forked the repo and successfully run yarn install. However, when I attempt to run yarn build, I encounter the following error:

```
file:///H:/somthing/icons/build.mjs:27
      console.error(iconsRes.stderr.toString());
                                    ^

TypeError: Cannot read properties of null (reading 'toString')
    at gen (file:///H:/somthing/icons/build.mjs:27:37)
    at file:///H:/somthing/icons/build.mjs:7:1
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.5.0
```

Could someone please help me understand what might be causing this issue and how I can resolve it?

Thank you!

**Comment by 2nthony** [comment]
Hi, I simply added an optional-chaining to `iconsRes.stderr` in 2f8074e8128347a10450cf93f460828f754b190c, maybe this fixed, but I think it should be platform path issue https://nodejs.org/api/path.html#pathnormalizepath, we use macOS & Linux

**Comment by AMIRKHANEF** [comment]
Hi,

Thank you for your response. I discovered the issue on my end and have resolved it.

Best regards.
